[[main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 1

[[main]]
    identifier = "about-sjucc"
    name = "About SJUCC"
    url = "/about-sjucc/"
    parent = "about"
    weight = 1

[[main]]
    identifier = "about-wpc"
    name = "About WPC"
    url = "/about-wpc/"
    parent = "about"
    weight = 2

[[main]]
    identifier = "projects"
    name = "Programs"
    url = "/projects/"
    weight = 2

#[[main]]
#    identifier = "contact"
#    name = "Contact"
#    url = "/contact/"
#    parent = "work"
#    weight = 3

[[main]]
    # Top-level menu entry
    identifier = "news"
    name = "News"
    url = "/posts/"
    weight = 3

[[main]]
    identifier = "donate"
    name = "Donate"
    url = "https://www.givelify.com/donate/st-john-s-ucc-jackson-mi-2j7wy5NzcyMDU=/donation/amount"
    weight = 4